server:
  port: 18080
  servlet:
    session:
      timeout: 30d

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intro
    username: root
    password: 248655
  application:
    name: SHUA

mybatis:
  mapper-locations: classpath:mapper/*.xml

web:
  url: "http://localhost:18000/"

